### ISSUE TITLE
発注者として、お弁当発注が成立したかを毎日投稿するのはめんどくさいので変えたい

### ISSUE THREAD

**Issue by yucao24hours** [colorbox/bento#103]
同じ定型文を同じチャンネル（たぶん idobata の room ）に毎日のように投稿するのはめんどう（だと思う）ので自動にしたい。

**Comment by yucao24hours** [comment]
原則的には、 `お弁当屋さんが指定している下限数よりも少なければ発注不成立、下限数以上ならば発注成立` っていう条件分岐で投稿メッセージを変えて post すればいいと思う。

現実的に運用している中で、下限数に達してなくても発注できたとか、下限数以上だったのに発注できなかった（しなかった）とかいうケースも出てくるかもしれないけど、今は想像がつかないので、そういうケースが出てきたときに対応する、でいいと思う。

**Comment by yucao24hours** [comment]
この post 、たぶん東京支社全体用のチャンネルに投稿するようになると思うけど（全員が揃っているのが今はそこしかないので）、それでいいのかな。お弁当ぜったい頼まない人、すなわちお弁当にぜったい関わらない人にとってはうっとうしい気もする。

という懸念があることも残しておきます。

**Comment by colorbox** [comment]
発注の成立に関しては、bentoのトップページに記載する
さらに追加情報として、idobataのユーザールームを作成し、そこに発注の成立情報を投稿させる

というのはどうでしょう？
基本的に必要な情報はbentoのページに行けば分かる、というふうにしておき、idobataからの通知が欲しい人にはidobataのユーザールームに入ってもらう、という具合です。

**Comment by tkm-kj** [comment]
マージ && 本番環境に環境変数が設定されていることを確認したのでclose
