### ISSUE TITLE
管理画面にメールにコピペして使えるように、注文されてる弁当とその個数を表示させたい

### ISSUE THREAD

**Issue by tkm-kj** [colorbox/bento#106]
フィードバックより。

注文する時にメールで行うという運用ができそうなので、そこに貼り付けるための弁当の種類と個数の一覧をコピペ出来るようにさせたい。

## やりたいこと

注文を締めた時、以下のようなテンプレートを管理画面に表示させる（これは1例なので、より良いものがあればそのように直して頂けると 🙇 ）。

```
（日付の情報）
弁当A: 2個
弁当C: 1個
```

0個の弁当は表示させないこと。

**Comment by yucao24hours** [comment]
>注文を締めた時、以下のようなテンプレートを管理画面に表示させる。

便利そう 👍 
発注する人の手間はできるだけ減らしてあげたいですよね。

ところで、具体的にどうやって機能を実装させるかっていうのを先に特定の人の判断できめてしまうと、「そうじゃないといけない」っていう考えに固定されてしまうのがこわいので、feature の実装のときにはひとまず「したいこと」だけ書いとけばいいかなとおもいました！（この issue に限らず）
そのためにわざわざ「計画づくり」というフェーズが存在するわけだし、そこでチームみんなの意見をあわせながらよりよい解決方法を見つけられればいいなという気持ちです。

**Comment by tkm-kj** [comment]
> 具体的にどうやって機能を実装させるかっていうのを先に特定の人の判断できめてしまうと、「そうじゃないといけない」っていう考えに固定されてしまうのがこわいので、feature の実装のときにはひとまず「したいこと」だけ書いとけばいいかなとおもいました！

確かに！実装の仕方は開発者に委ねる形で大丈夫ですね。

**Comment by yucao24hours** [comment]
ところでコレって #61 と dup なように見えるのだけどチョット違うのかな？

**Comment by colorbox** [comment]
> ところでコレって #61 と dup なように見えるのだけどチョット違うのかな？

dupで合ってます。
このissueは木曜日にヒヤリングした時に作成したもの、 #61 はそれよりも前に作成されたものです。
作成時期が異なるだけで言及しているものは同一なので、閉じるタイミングを同じにして対応すれば良いかなと思います。

**Comment by yucao24hours** [comment]
>作成時期が異なるだけで言及しているものは同一なので、閉じるタイミングを同じにして対応すれば良いかなと思います。

とのことなんですが、project ボードで見るとこういうコメントのやりとりとかが見えなくてどっちがどっちだかわからなくなるので、できればどちらか閉じてひとつにしてもらいたいです...
（どちらかにだけ書いてある情報があるなら片方に寄せればいいだけで、issue としてあえて重複させておく意味がわたしには見つけられなかったので 🙏 ）

**Comment by colorbox** [comment]
> issue としてあえて重複させておく意味がわたしには見つけられなかった

なるほど、たしかに重複したissueを残しておく意味は無いですね。
一旦こちらを閉じて、PRから参照されている #61 を残します。
