### ISSUE TITLE
ユーザとして、自分が明日のお弁当を注文し忘れていないかを確認したい。

### ISSUE THREAD

**Issue by yucao24hours** [colorbox/bento#12]

**Comment by tkm-kj** [comment]
これって https://app.moqups.com/colorbox222@gmail.com/IjJQsSFMcQ/view/page/a8612b543 の予約確認画面で自分の予約を確認できるってことですかね？
手が空いてるので取りたい気持ちがありますね。

**Comment by yucao24hours** [comment]
そうですね、つまり日付を指定してその日の予約一覧を見る、という行動になりそうだなと思います〜

**Comment by colorbox** [comment]
PRがマージされたのでcloseします。
