### ISSUE TITLE
ユーザ用ルームのアイコンを目立つ（わかりやすい）ものにしたい

### ISSUE THREAD

**Issue by yucao24hours** [colorbox/bento#125]
コード的に変えることではないけど...
毎日 idobata に投稿する Hook のアイコンを、よりわかりやすいものにしたい。もしくは、メッセージ自体を目立たせたい。
なぜなら、どれが「成立・不成立」のメッセージかすくわからないと、見落とす可能性があるし、さがすのがめんどうだから。

**Comment by yucao24hours** [comment]
見やすくなりました！
@colorbox ありがとうございました！

**Comment by colorbox** [comment]
👍
