### ISSUE TITLE
通知の環境を切り分ける

### ISSUE THREAD

**Issue by colorbox** [colorbox/bento#131]
### 目的
開発時にミスっても本番環境のユーザーに影響が無いようにしたい。

### 完了条件
テスト環境や開発環境で通知を飛ばさない、もしくは飛ばす先を変えるなどの切り分けをしたい。

**Comment by yucao24hours** [comment]
https://github.com/colorbox/bento/pull/127/commits/b564e632a912c772c22127633bca70472780cbfc

こういうことを意図してますかね？

**Comment by colorbox** [comment]
ですです。 👍 
テスト環境や開発環境で通知を飛ばさない、もしくは飛ばす先を変えるなどの切り分けをしたい感じです。
開発時にへたな事をしても本番環境のユーザーに影響がないようにしたいというのがこのISSUEの目的ですね。

**Comment by yucao24hours** [comment]
ちょっと気になったのですけど、実際に "開発時にミスって本番に影響があった" からできた issue なんですかね？
（もしそうだったら、そうなった状況を書いてもらったほうが実装しやすいかなと思ったのでした）

**Comment by colorbox** [comment]
「管理画面のデモを見せる際に通知を飛ばしかけた」
という感じですね。

あと少しで本番に影響出していた😰 
というのがこのissueを立てた時の状況です。

**Comment by yucao24hours** [comment]
>管理画面のデモを見せる際

ということなので、「今日のお弁当は成立しました（しませんでした）」のメッセージが post されるところだったということですかね。
それが起きた場面では、どの環境でアプリケーションを動かしていたんでしょうか？（ "あと少しで本番に影響出していた" ということなので、エンドポイントを指す環境変数に "本番で使っているエンドポイント URL" が設定されていた環境下だと予測しています。）

`close` 後の `Idobata#post` の動作も含めてデモする必要性があった場面で、もし本番環境を用いていたのだとしたらそもそもそれは本番環境を使うことが目的にあっていないので、解決策は「本番環境ではないところで動かす」になると思います。

尤もそれは、本番環境以外では 環境変数 `IDOBATA_USER_HOOK_URL` に "本番で使っているエンドポイント URL" は設定されていないという前提のもとの話です。
開発環境で `IDOBATA_USER_HOOK_URL` に本番で使っているエンドポイント URL が設定されていて、そのせいで（本番環境以外を使ってデモしていたのに）本番用 room に post されそうになったということだとしたらその値が設定されているという状況がアプリケーション開発・運用を進める上で現実的ではなく不自然に思えるので、環境変数に設定する URL を違う値にする（厳密には、開発用の idobata room を作るなどしてそれのエンドポイントを設定する）ことで解決になるんじゃないかなと思います。

ちょっと状況がいまいちはっきり想像ついてないところもあって、やるべきこととかがあまりわかっていないです。すみません。

**Comment by colorbox** [comment]
デモ作業当時はローカルでやっていたのですが、前に作業していたフック用URLが環境変数に入っていた状態でした。

> 環境変数に設定する URL を違う値にすることで解決になるんじゃないかなと思います。

上記の対応で解決するので一旦closeします。お騒がせしました 🙇
