### ISSUE TITLE
発注者として、「今日は発注作業が必要かどうか」を知りたい

### ISSUE THREAD

**Issue by yucao24hours** [colorbox/bento#134]
なぜなら、"お弁当予約が成立しました。お弁当屋さんに発注作業をお願いします" のような文言が出てくれたほうが、人間側で判断する必要がなくなってラクだし、（可能性としては低いと思うけど）ミスの防止にもなるからだ。

## 背景
今の admin 画面には、「今日は発注作業（メール or FAX で）発注作業が必要かどうか」の情報がどこにも出ていないので、表の `合計` 欄を見て自分で判断しないといけないため、多少面倒である。
（「成立していたらメールテンプレが表示されるような条件分岐は入っているので、それが表示されたら「発注作業がいるんだな」と判断できなくもないけど、本来それを目的として作られた機能ではない）

**Comment by tkm-kj** [comment]
![2017-05-13 15 26 19](https://cloud.githubusercontent.com/assets/3395349/26023134/8c4f4a46-37f0-11e7-8ea1-338b8f934e65.png)

確かに、これだと管理者が次何すればいいかのアクションが何もないですね。。。
注文可能数なら「発注してください」、注文できなかったら「注文数に達しませんでした」のような次のアクションを促すメッセージを表示させるのはありかもと思いました。

**Comment by tkm-kj** [comment]
新卒氏にやってもらうとすごくありがたいかも！

**Comment by tkm-kj** [comment]
thanx @hisas
