### ISSUE TITLE
ワイヤ作成

### ISSUE THREAD

**Issue by yucao24hours** [colorbox/bento#20]
## 完了条件
2017/03/01のミーティングで話したことをもとに、みんなが見えるところにアップロードする。

**Comment by colorbox** [comment]
とりあえず作りました。
https://app.moqups.com/colorbox222@gmail.com/IjJQsSFMcQ/view/page/aa8500b8c


前回お見せしたものからの差分としては
 - 発注者用の画面を追加
 - 予約確認画面でキャンセルを可能に
    - 合わせて、予約編集画面での予約キャンセルを削除
 
などですー

**Comment by yucao24hours** [comment]
ひとまずこちらは close でいいかな？

**Comment by colorbox** [comment]
closeします 📕
