### ISSUE TITLE
注文日選択を日付順にしたい

### ISSUE THREAD

**Issue by tkm-kj** [colorbox/bento#58]
## 背景

注文日選択が以下のように日付順に並ばない可能性があるので、日付順に並ぶように修正したい。

![2017-03-21 10 59 43](https://cloud.githubusercontent.com/assets/3395349/24129368/94266726-0e25-11e7-85b3-687a37f72c19.png)

## 完了条件

- https://github.com/colorbox/bento/blob/53-freeze-order/app/models/order.rb#L21 にdate昇順の条件をつける。
- テスト

**Comment by tkm-kj** [comment]
https://github.com/colorbox/bento/blob/53-freeze-order/app/models/order.rb#L23 のコードも Order 生成するところで休日祝日抜いてるから無くても良さげ。

**Comment by yucao24hours** [comment]
https://github.com/colorbox/bento/pull/32#issuecomment-285057027

仮でいれてました。Order レコードつくるところでそこは取りますね。

**Comment by yucao24hours** [comment]
これ、 #42 で Order の前提条件（土日祝日がなくなる）ので、`on_weekday` というインスタンスメソッドをなくして、コントローラ `order#index` に

```ruby
def index
  @orders = Order.where('date > ?', Time.current.to_date).limit(14).order(date: :asc)
end
```

って書くだけにできちゃうんじゃないかなーと思っております 💭 （ `where` 以降が長くてちょっとな〜ってことならもちろん `scope` とかを定義してもいいとおもいます）

**Comment by tkm-kj** [comment]
確かにModelに寄せなくても良さそうですね！
2週間出すなら10営業日なので `limit(10)` の方がより厳密かなと（とはいえ、そこまで厳密にする必要もないのでおまかせですけど）

**Comment by colorbox** [comment]
🔚 to close
