### ISSUE TITLE
管理者として締めた後に業者に送るためのメールをコピペ出来るようにしたい

### ISSUE THREAD

**Issue by tkm-kj** [colorbox/bento#61]
## 背景

管理者が注文を締め切った後に業者に弁当を頼むためにメールすることになるが、そのメールを楽に出せるようにするためにどの弁当をいくつ頼むかという内容のメール本文をすぐに書ける方が良いという要望があったため。

## 完了条件

注文を締めた後、注文確認画面にメールにコピペするための文言（注文内容等）が表示されるようになっている。
テンプレは管理者と相談で。

**Comment by yucao24hours** [comment]
現状は FAX でできているので、最初のリリース以降にする。

**Comment by colorbox** [comment]
FYI)
重複issue #106 での議論も参照されたし
