### ISSUE TITLE
注文を締め切った注文日は、トップページに表示させない

### ISSUE THREAD

**Issue by yucao24hours** [colorbox/bento#63]
そもそも注文できないのに表示してるのは不自然だし、使う人にとってもまぎらわしいので。

**Comment by tkm-kj** [comment]
修正箇所が #58 と同じなので一緒にやりたいですな

**Comment by yucao24hours** [comment]
`closed_at?` が入っていたら（close されていたら）トップ画面では「受け取りページはこちら」みたいなリンク？ボタン？を表示するようにする。

**Comment by colorbox** [comment]
終わってるっぽいのでcloseします
