### ISSUE TITLE
i18n で表示文言を統一したい

### ISSUE THREAD

**Issue by yucao24hours** [colorbox/bento#67]
- `Back` など繰り返し出てくる表記はできるだけ一箇所で定義しておきたい。
- `customer_name` などモデルに紐づく表記は `label` ヘルパーなどでも使われるので、i18n のしくみを使って定義しておきたい。

**Comment by yucao24hours** [comment]
> `customer_name` などモデルに紐づく表記は `label` ヘルパーなどでも使われるので、i18n のしくみを使って定義しておきたい。

これは既に #76 で対応済み

**Comment by colorbox** [comment]
close via #68
