### ISSUE TITLE
customer name（注文者名）が空欄でも注文できてしまう

### ISSUE THREAD

**Issue by yucao24hours** [colorbox/bento#69]
誰が注文したのかわからないし、そもそも入力ミスの可能性もあるしで、お弁当の注文者の方が困ってしまいそう。
customer_name は必須になるようにしたい。

**Comment by colorbox** [comment]
優先度が高いカードが有るのだけれど、そちらは他のPRがマージされないと着手しづらそうなのでこちらを先に着手します。

**Comment by yucao24hours** [comment]
close via #75
