### ISSUE TITLE
アプリ内の表記を統一したい（「注文」と「予約」）

### ISSUE THREAD

**Issue by yucao24hours** [colorbox/bento#72]
アプリ内で `注文` と `予約` という単語が出てくるが、これらは両方とも実質的には同じものを指していると思うので、どちらかに統一したい。
アプリ使用者にとっては、なにか使い分けがあるのかと考えて混乱してしまうと思う。
開発者にとっては、なにかあったときに grep しづらいので、修正漏れが出るおそれがある。

**Comment by yucao24hours** [comment]
`注文` だと、総務の方がお弁当屋さんに FAX する行為（今は `発注` と呼んでいるやつ）と混同してしまう気がする（細かい話だけど、 `注` の字が一緒だし...）。
一方で `予約` ってのも厳密にはなんか違うきもする。

でも統一されてないのは嫌なので、直したい...

**Comment by tkm-kj** [comment]
#92 で完了
